name: Simple Test

on:
  push:
    branches: [main, test]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Hello from GitHub Actions!"

      - name: Current time
        run: date

      - name: Test SSH connection
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "SSH connection successful!"
            echo "Server: $(hostname)"
            echo "User: $(whoami)"
            echo "Time: $(date)"
